# created by pngn7105 02.10.2026
# tree in step 6 is installed for debugging
name: Build tctiSH IPA

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build IPA
    runs-on: xcode-27
    env:
      UPLOAD_IPA: ${{ vars.UPLOAD_IPA || 'true' }}

    steps:
      - name: 1. Fetch Source Code
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: 2. Set Up Nix
        run: |
          curl --proto '=https' --tlsv1.2 -L https://nixos.org/nix/install | sh
          echo "/nix/var/nix/profiles/default/bin" >> "$GITHUB_PATH"
          mkdir -p "$HOME/.config/nix"
          echo "experimental-features = nix-command flakes" >> "$HOME/.config/nix/nix.conf"

      - name: 3. Configure Xcode Environment
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "latest"

      - name: 4. Build App and Dependencies
        run: |
          make build GUEST=prebuilt SKIP_CODESIGNING=1

      - name: 5. Build with Xcode
        run: |
          xcodebuild \
            -project $GITHUB_WORKSPACE/tctiSH.xcodeproj \
            -scheme "tctiSH" \
            -configuration Release \
            -derivedDataPath $RUNNER_TEMP/BuildDerivedData \
            -resolvePackageDependencies \
            ONLY_ACTIVE_ARCH=NO 
          xcodebuild \
            -project $GITHUB_WORKSPACE/tctiSH.xcodeproj \
            -scheme "tctiSH" \
            -configuration Release \
            -derivedDataPath "$RUNNER_TEMP/BuildDerivedData" \
            -destination "generic/platform=iOS" \
            ONLY_ACTIVE_ARCH=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            PROVISIONING_PROFILE_SPECIFIER="" \
            build

      - name: 6. Package .app into .ipa
        env:
          APP_PATH: ${{ runner.temp }}/BuildDerivedData/Build/Products/Release-iphoneos/tctiSH.app
          IPA_PATH: ${{ runner.temp }}/tctiSH.ipa
        run: |
          brew install tree
          tree
          mkdir -p "$RUNNER_TEMP/Payload"
          cp -R "$APP_PATH" "$RUNNER_TEMP/Payload/"
          zip -r tctiSH.zip $RUNNER_TEMP/Payload
          mv $RUNNER_TEMP/tctiSH.zip $RUNNER_TEMP/tctiSH.ipa

      - name: 7. Store IPA as Workflow Artifact
        if: env.UPLOAD_IPA == 'true'
        uses: actions/upload-artifact@v7
        with:
          name: tctiSH.ipa
          path: ${{ runner.temp }}/tctiSH.ipa
          retention-days: 90
          if-no-files-found: error
